src/Entity/Item.php
<?php

namespace App\Entity;

use App\Repository\ItemRepository;
use AssertionError;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ItemRepository::class)]
#[Broadcast]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "El título no puede estar vacío")]
    private ?string $titulo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $descripcion = null;

    #[ORM\Column(length: 255)]
    private ?string $foto = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[Assert\NotBlank(message: "Debe de existir una localidad")]
    private ?Localidad $Localidad = null;

    #[ORM\ManyToMany(targetEntity: Ruta::class, inversedBy: 'items')]
    private Collection $Ruta;

    public function __construct()
    {
        $this->Ruta = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setID(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): static
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(string $foto): static
    {
        $this->foto = $foto;

        return $this;
    }

    public function getLocalidad(): ?Localidad
    {
        return $this->Localidad;
    }

    public function setLocalidad(?Localidad $Localidad): static
    {
        $this->Localidad = $Localidad;

        return $this;
    }

    /**
     * @return Collection<int, Ruta>
     */
    public function getRuta(): Collection
    {
        return $this->Ruta;
    }

    public function addRutum(Ruta $rutum): static
    {
        if (!$this->Ruta->contains($rutum)) {
            $this->Ruta->add($rutum);
        }

        return $this;
    }

    public function removeRutum(Ruta $rutum): static
    {
        $this->Ruta->removeElement($rutum);

        return $this;
    }
}

templates/filtro.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!--IE priority -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=IE">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="DuongHailee">
    <meta name="author" content="DuongHaiLee, Jacky, Hailee">
    <meta name="keywords" content="portfolio, full-stack developer, metropolia UAS">

    
    <script src="{{asset('js/jquery-3.7.1.js')}}"></script>
    <script src="{{asset('js/jquery-ui.js')}}"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{asset('css/jquery-ui.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery-ui.structure.css')}}">
    <link rel="stylesheet" href="{{asset('css/jquery-ui.theme.css')}}">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('css/landing.css') }}">

    <script src="{{asset('js/main.js')}}"></script>
    <style>
        .container {
            max-width: 1200px;
            margin: 20px auto;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .tour {
            width: 300px;
            border: 1px solid #ddd;
            margin: 10px;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s;
        }

        .tour:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        .tour img {
            max-width: 100%;
            height: auto;
        }

        .tour h2 {
            font-size: 1.5em;
            margin-bottom: 10px;
        }

        .tour p {
            color: #666;
        }

        .tour a {
            display: inline-block;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            padding: 8px 15px;
            margin-top: 10px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .tour a:hover {
            background-color: #555;
        }
		.pagination {
			display: flex;
			justify-content: center;
			margin-top: 20px;
		}

		.pagination .pagination-wrapper {
			display: flex;
			list-style: none;
			padding: 0;
			margin: 0;
		}
		.pagination .pagination .current{
			border: 1px solid black;
			text-decoration:none;
			padding: 20px;
			background-color: #dddbdb;
		}

		.pagination .pagination .page a{
			text-decoration: none;
			color: black;
		}

		.pagination .pagination .page {
			border: 1px solid black;
			text-decoration: none;
			color: black;
			padding: 20px;
			background-color: #dddbdb;
		}

		.pagination .pagination .page:hover,.pagination .pagination .current:hover {
			background-color: #c0bebe;
		}

		.last a,.next a,.first a,.previous a{
			text-decoration: none;
			color: black;
		}

		.last,.next,.first,.previous{
			padding: 20px;
		}
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 1200px;
            margin: 20px auto;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .tour {
            width: 300px;
            border: 1px solid #ddd;
            margin: 10px;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s;
        }

        .tour:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        .tour img {
            max-width: 100%;
            height: auto;
        }

        .tour h2 {
            font-size: 1.5em;
            margin-bottom: 10px;
        }

        .tour p {
            color: #666;
        }

        .tour a {
            display: inline-block;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            padding: 8px 15px;
            margin-top: 10px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .tour a:hover {
            background-color: #555;
        }
    </style>
</head>
<body>
{% block body %}
    {% include "header.html.twig" %}
    <div class="container">
    {% if tours is empty %}
            <p class="text-center" style="color:red;"> No existen tours con los filtros que usó </p>
        {% else %}
            {% for tour in tours %}
                    <div class="tour">
                        <img src="{{asset('css/imagenes/'~ tour.ruta.foto)}}" alt="Tour">
                        <h2>{{tour.ruta.titulo}}</h2>
                        <p>{{tour.ruta.descripcion|raw}}</p>
                        {% if not app.user %}
                            <a href="{{ path('app_info_tour', {'id_tour': tour.id}) }}">Ver más</a>
                        {% else %}
                            <a href="{{ path('app_info_tour', {'id_tour': tour.id, 'id_user': app.user.id}) }}">Ver más</a>
                        {% endif %}
                    </div>
            {% endfor %}
        {% endif %}
    </div>
    {% if not app.user %}
                <div id="miModal">
                    {% if error %}
                        <div>{{ error.messageKey|trans(error.messageData, 'security')}}</div>
                    {% endif %}

                    <form action="{{ path('app_main') }}" method="post">
                        <label for="username">Email:</label>
                        <input type="text" id="username" name="_username" value="{{ last_username }}">

                        <label for="password">Contraseña:</label>
                        <input type="password" id="password" name="_password">

                        <input type="hidden" name="_target_path" value="/main">

                        <button type="submit">Iniciar Sesión</button>
                    </form>
                </div>
    {% endif %}
    <div class="pagination">
        {{knp_pagination_render(tours)}}
    </div>
{% endblock %}
</body>
</html>

templates/infoTour.html.twig
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=IE">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Descripción del sitio">
    <meta name="author" content="Autores del sitio">
    <meta name="keywords" content="Palabras clave">

    <!-- Librerías JavaScript externas -->
    <script src="{{ asset('js/jquery-3.7.1.js') }}"></script>
    <script src="{{ asset('js/jquery-ui.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Librerías CSS externas -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/jquery-ui.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery-ui.structure.css') }}">
    <link rel="stylesheet" href="{{ asset('css/jquery-ui.theme.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>

    <!-- Estilos personalizados -->
    <link rel="stylesheet" href="{{ asset('css/landing.css') }}">

    <script src="{{ asset('js/info.js') }}"></script>
    <script src="{{ asset('js/main.js') }}"></script>

    <title>{{ tour.ruta.titulo }}</title>
    <style>
        #reserva_num_personas{
            height: 60%;
            margin-top: 2%;
        }
    </style>
</head>
<body>
    {% block body %}
        {% include "header.html.twig" %}
        <main id="main" data-id="{{tour.id}}">
            <h2 style="color: #f70759; text-align: center;">{{ tour.ruta.titulo }}</h2>

            <!-- Carrusel de Imágenes -->
            <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for item in items %}
                        <div class="carousel-item {% if loop.first %}active{% endif %}">
                            <img src="{{ asset('css/imagenes/' ~ item.foto) }}" class="d-block w-100 img-fluid" style="max-height: 100px;">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>

            <!-- Contenido Principal -->
            <div class="container-fluid mt-5">
                <!-- Encabezado del Tour -->
                <div class="jumbotron">
                    <h1 class="display-4">Tour en la Ciudad</h1>
                    <p class="lead">Descubre los lugares más fascinantes de nuestra hermosa ciudad.</p>
                </div>

                <!-- Información del Tour -->
                <div class="row">
                    <div class="col-md-6">
                        <!-- Detalles del Tour -->
                        <p><strong>Fecha:</strong> {{ tour.fecha|date('d/m/Y') }}</p>
                        <p><strong>Hora de inicio:</strong> {{ tour.hora|date('H:i:s') }}</p>
                        <p><strong>Punto de encuentro:</strong></p>
                        <div id="mapa" style="height: 300px;"></div>
                        <p><strong>Aforo:</strong> {{ tour.ruta.aforo }} personas</p>
                    </div>
                    <div class="col-md-6">
                        <!-- Descripción del Tour y Reserva -->
                        <h2>Descripción</h2>
                        <p>{{ tour.ruta.descripcion|raw }}</p>

                        <!-- Mensajes Flash y Formulario de Reserva -->
                        {% for flash_message in app.session.flashbag.get('exito') %}
                            <div class="alert alert-success">{{ flash_message }}</div>
                        {% endfor %}

                        {% for flash_message in app.session.flashbag.get('Error') %}
                            <div class="alert alert-success">{{ flash_message }}</div>
                        {% endfor %}
                        {% for error in errores %}
                            <div class="alert alert-danger">{{ error.message }}</div>
                        {% endfor %}

                        {% for flash_message in app.session.flashbag.get('Aforo') %}
                            <div class="alert alert-danger">{{ flash_message }}</div>
                        {% endfor %}
                        <div class="d-flex align-items-center mt-4">
                            <div class="btn-group mt-4" role="group">
                                <button class="btn btn-outline-secondary" type="button" id="resta">-</button>
                                <button class="btn btn-outline-secondary" type="button" id="suma">+</button>
                            </div>
                            {{ form_start(form) }}
                                <label for="{{ form.num_personas.vars.id }}">Num personas</label>
                                <div class="input-group">
                                    {{ form_widget(form.num_personas, {'attr': {'class': 'form-control ms-2'}}) }}
                                    {% if tour.Reserva is not empty %}
                                        {% set usuarioReservo = false %}
                                        {% for reserva in tour.Reserva %}
                                            {% if reserva.Usuario == app.user %}
                                                {% set usuarioReservo = true %}
                                                <input type="submit" class="btn btn-primary h-50 ms-2 mt-1" value="RESERVADO" disabled>
                                            {% endif %} 
                                        {% endfor %}
                                        {% if not usuarioReservo %}
                                            <input type="submit" class="btn btn-primary h-50 ms-2 mt-1" value="RESERVAR">
                                        {% endif %}
                                    {% else %}
                                        <input type="submit" class="btn btn-primary h-50 ms-2 mt-1" value="RESERVAR">
                                    {% endif %}

                                </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal de Inicio de Sesión -->
            {% if not app.user %}
                <div id="miModal">
                    {% if error %}
                        <div>{{ error.messageKey|trans(error.messageData, 'security')}}</div>
                    {% endif %}

                    <form action="{{ path('app_main') }}" method="post">
                        <label for="username">Email:</label>
                        <input type="text" id="username" name="_username" value="{{ last_username }}">

                        <label for="password">Contraseña:</label>
                        <input type="password" id="password" name="_password">

                        <input type="hidden" name="_target_path" value="/main">

                        <button type="submit">Iniciar Sesión</button>
                    </form>
                </div>
            {% endif %}
        </main>
    {% endblock %}
</body>
</html>

templates/landingpage.html.twig
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=IE">
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<!-- Estilos -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{{asset('css/jquery-ui.css')}}">
		<link rel="stylesheet" href="{{asset('css/jquery-ui.structure.css')}}">
		<link rel="stylesheet" href="{{asset('css/jquery-ui.theme.css')}}">
		<link rel="stylesheet" href="{{asset('css/landing.css')}}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

		<!-- Scripts -->
		<script src="{{asset('js/jquery-3.7.1.js')}}"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
		<script src="{{asset('js/jquery-ui.js')}}"></script>
		<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker@3.1.0/daterangepicker.css"/>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
		<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker@3.1.0/daterangepicker.js"></script>
		<script src="{{asset('js/main.js')}}"></script>

		
		<style>
        /* Estilos CSS en línea para propósitos de este ejemplo */
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            max-width: 1200px;
            margin: 20px auto;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .tour {
            width: 300px;
            border: 1px solid #ddd;
            margin: 10px;
            padding: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            transition: box-shadow 0.3s;
        }

        .tour:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        .tour img {
            max-width: 100%;
            height: auto;
        }

        .tour h2 {
            font-size: 1.5em;
            margin-bottom: 10px;
        }

        .tour p {
            color: #666;
        }

        .tour a {
            display: inline-block;
            background-color: #333;
            color: #fff;
            text-decoration: none;
            padding: 8px 15px;
            margin-top: 10px;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .tour a:hover {
            background-color: #555;
        }
		.pagination {
			display: flex;
			justify-content: center;
			margin-top: 20px;
		}

		.pagination .pagination-wrapper {
			display: flex;
			list-style: none;
			padding: 0;
			margin: 0;
		}
		.pagination .pagination .current{
			border: 1px solid black;
			text-decoration:none;
			padding: 20px;
			background-color: #dddbdb;
		}

		.pagination .pagination .page a{
			text-decoration: none;
			color: black;
		}

		.pagination .pagination .page {
			border: 1px solid black;
			text-decoration: none;
			color: black;
			padding: 20px;
			background-color: #dddbdb;
		}

		.pagination .pagination .page:hover {
			background-color: #c0bebe;
		}

		.last a,.next a,.first a,.previous a{
			text-decoration: none;
			color: black;
		}

		.last,.next,.first,.previous{
			padding: 20px;
		}
		
    </style>
	</head>
	<body>
		{% block body %}
			{% include "header.html.twig" %}
			<main id="civ-main-element">
    			<header class="o-head _home _relative">
        			<picture class="o-head__img__container">
            			<source media="(max-width: 767px) and (orientation: portrait)" srcset="https://www.civitatis.com/f/images/banners/home-07-m.jpg">
            			<img src="https://www.civitatis.com/f/images/banners/home-07.jpg" alt="Civitatis">
        			</picture>
					<div class="o-head__content">
						<div class="__inner">
						<p class="o-head__subtitle">
							Llena
							<strong>tu viaje</strong>
						</p>
						<h1 class="o-head__title">Visitas guiadas y excursiones en español por todo el mundo</h1>
					</div>

					<div class="r-home-search" id="home-search-parent">
						<div class="o-home-search row">
							<div class="o-home-search__label">buscar</div>
							<div class="o-home-search__form-container">
								<div class="o-home-search__form">
									<form method="get" id="o-home-search__form--ywwhm" action="/es/buscar">
										<div class="o-search-container d-flex" id="home-search-container">
											<input type="hidden" name="q" value="">
											<div class="o-search-container__search-txt d-flex">
												<input aria-label="buscar" id="home-search-text" autocomplete="off" type="text" placeholder="¿Dónde quiere viajar?" maxlength="50" value="">
												<input id="fecha" type="text" style="margin-left: 3%;margin-right: 3%; width: 100%;">
											</div>
											<input type="submit" class="o-search-container__search-button" id="page-header__search-button" style="background-color: #f70759; border-radius: 12px;" value="BUSCAR">
										</div>
									</form>
								</div>
							</div>
							<div class="o-home-search__list__container ua-resizeable u-transparent" id="o-home-search__list__container"></div>
								<div class="o-home-search__filtered-list__container ua-resizeable u-transparent" id="o-home-search__filtered-list__container"></div>
							</div>
						</div>
					</div>
				</header>
				<div id="miModal">
        {% if error %}
            <p style="color: red;">{{error.messageKey|trans(error.messageData, 'security')}}</p>
        {% endif %}
        
        <form method="post">
            <div class="d-flex mb-2">
                <label for="username">Email:</label>
                <input type="text" id="username" name="_username" value="{{ last_username }}">
            </div>
            <div class="d-flex">
                <label for="password">Password:</label>
                <input type="password" id="password" name="_password">
            </div>
            <input type="hidden" name="_target_path" value="/rol"> 

            <input type="submit" class="btn btn-primary" value="LOGIN">
        </form>
    </div>
    <div class="container mt-4">
        <div class="row">
			<h2 id="tit" style="text-align: center;"> Tours mejores valorados</h2>
            {% for tour in pagination %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="tour">
                        <img src="{{asset('css/imagenes/'~ tour.ruta.foto)}}" alt="Tour" class="img-fluid">
                        <h2>{{tour.ruta.titulo}}</h2>
                        <p>{{tour.ruta.descripcion|raw}}</p>
                        {% if app.user %}
                            <a href="{{path('app_info_tour',{id_tour: tour.id,id_user:app.user.id})}}" class="btn btn-primary">Ver más</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="pagination mt-4">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</main>
{% endblock %}
</body>
</html>

templates/lista.html.twig
<html>
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=IE">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Estilos -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{{asset('css/jquery-ui.css')}}">
		<link rel="stylesheet" href="{{asset('css/jquery-ui.structure.css')}}">
		<link rel="stylesheet" href="{{asset('css/jquery-ui.theme.css')}}">
		<link rel="stylesheet" href="{{asset('css/landing.css')}}">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">

		<!-- Scripts -->
		<script src="{{asset('js/jquery-3.7.1.js')}}"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
		<script src="{{asset('js/jquery-ui.js')}}"></script>
		<script src="{{asset('js/main.js')}}"></script>
    </head>
    <body>
        {% block body %}
		{% include "header.html.twig" %}
		<div class="container mt-5">
        <h1 class="display-4 text-center mb-4">Descubre Nuestros Exclusivos Tours</h1>

        <div class="row justify-content-center" style="margin-top: 4%;">
            <div class="col-lg-8">
                <div class="card-deck">
                    {% for tour in tours %}
                        {% set fecha_actual = "now"|date("Y-m-d H:i:s") %}
                        {% set fecha_tour = tour.fecha|date("d/m/Y") ~ ' ' ~ tour.hora|date("H:i:s") %}

                        {% set fecha_actual = "now"|date("Y-m-d H:i:s") %}
                        {% set fecha_tour = tour.fecha|date("Y-m-d") ~ ' ' ~ tour.hora|date("H:i:s") %}

                        {% set diferencia_segundos = fecha_actual|date("U") - fecha_tour|date("U") %}
                        {% set diferencia_minutos = (diferencia_segundos / 60)|round %}
                        {% if fecha_actual <= fecha_tour and diferencia_minutos <= 5 %}
                            <div class="card mb-5">
                                <img src="{{ asset("css/imagenes/" ~ tour.ruta.foto) }}" class="card-img-top" alt="{{ tour.ruta.titulo }}">

                                <div class="card-body">
                                    <h5 class="card-title">{{ tour.ruta.titulo }}</h5>
                                    <p class="card-text text-muted">{{ tour.ruta.descripcion|raw }}</p>
                                </div>
                                {% if tour.getNumPersonasAsisten %}
                                    <div class="card-footer d-flex justify-content-between align-items-center">
                                        <input type="button" class="btn btn-primary" value="LISTADO" disabled>
                                    </div>
                                {% else %}
                                    <div class="card-footer d-flex justify-content-between align-items-center">
                                        <a href="{{ path('app_pasarlista', { 'id': app.user.id, 'id_tour': tour.id }) }}" class="btn btn-primary btn-sm">Pasar Lista</a>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                {% if tours is empty %}
                    <p class="text-center text-muted mt-4">¡Próximamente nuevos tours! Mantente atento.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>